### PR TITLE
Added javascript example for normal people

### PR DESCRIPTION
**Pull request by nathanhornby**

### CODE REVIEW

**Comment by glumb** [comment]
Thanks. Not everyone is riding on the hipster train.

**Comment by ccorcos** [comment]
ah man, gotta love coffeescript :) haha. I've been moving to ES6 actually. Had to get [one of these keyboards](http://www.amazon.com/Kinesis-KB500USB-BLK-Advantage-Contoured-Keyboard/dp/B000LVJ9W8) though to easy my pinkies from all the strain on hose parentheses and braces!

**Comment by nathanhornby** [comment]
Purists unite! I've been learning elixir and I do enjoy the punctuation-less syntax, but coffeescript is so dirty and wrong and you should feel bad for using it :D

**Comment by ccorcos** [comment]
Dirty and wrong?! Why do you think so?

**Pull request merged**
